# Generated by Django 5.1.4 on 2024-12-26 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
